language: python
python:
  - '2.7'
before_install:
  - currentfolder=${PWD##*/}
  - if [ '$currentfolder' != 'generator-django-kaiju' ]; then cd .. && eval 'mv $currentfolder generator-django-kaiju' && cd generator-django-kaiju; fi
install:
  - 'npm install'
  - 'pip install django'
script: 'npm test'
